"""
SwitchGate - Brave-Grade Curated Adblock & Tracker Filter Rules
Based on Brave Shields, EasyList, EasyPrivacy, and uBlock Origin rule specifications.
"""

BRAVE_ADBLOCK_RULES = [
    # Top Global Ad Networks & Exchange Networks
    "||doubleclick.net^",
    "||googleadservices.com^",
    "||googlesyndication.com^",
    "||adnxs.com^",
    "||taboola.com^",
    "||outbrain.com^",
    "||criteo.com^",
    "||rubiconproject.com^",
    "||pubmatic.com^",
    "||openx.net^",
    "||casalemedia.com^",
    "||smartadserver.com^",
    "||advertising.com^",
    "||adcolony.com^",
    "||unityads.unity3d.com^",
    "||applovin.com^",
    "||ironsrc.com^",
    "||vungle.com^",
    "||chartboost.com^",
    "||inmobi.com^",
    "||mopub.com^",
    "||popads.net^",
    "||popcash.net^",
    "||propellerads.com^",
    "||adcash.com^",
    "||clickadu.com^",
    "||yllix.com^",
    "||bidvertiser.com^",
    "||adsterra.com^",
    "||revcontent.com^",
    "||mgid.com^",
    "||adroll.com^",
    "||quantserve.com^",
    "||scorecardresearch.com^",
    "||aax.amazon-adsystem.com^",
    "||c.amazon-adsystem.com^",
    "||s.amazon-adsystem.com^",
    "||fls-na.amazon.com^",
    "||adservice.google.com^",
    "||adservice.google.co.in^",
    "||adservice.google.co.uk^",
    "||googletagservices.com^",
    "||googletagmanager.com^",
    "||partnerad.l.google.com^",
    "||pagead.l.google.com^",
    
    # Telemetry, Analytics & Tracker Pixels (EasyPrivacy)
    "||google-analytics.com^",
    "||analytics.google.com^",
    "||hotjar.com^",
    "||clarity.ms^",
    "||mixpanel.com^",
    "||segment.io^",
    "||amplitude.com^",
    "||branch.io^",
    "||appsflyer.com^",
    "||adjust.com^",
    "||kochava.com^",
    "||singular.net^",
    "||facebook.com/tr/^",
    "||connect.facebook.net/en_US/fbevents.js",
    "||tiktok.com/api/v1/pixel^",
    "||ads-twitter.com^",
    "||statcounter.com^",
    "||yandex.ru/metrika^",
    "||mc.yandex.ru^",

    # Video Prerolls, In-Stream Ads & YouTube Ad Sinks (Safe: Video Content Preserved)
    "||youtube.com/api/stats/ads^",
    "||youtube.com/pagead/^",
    "||youtube.com/ptracking^",
    "||s.youtube.com/api/stats/ads^",
    "||googleads.g.doubleclick.net^",
    "||pagead2.googlesyndication.com^",
    "||ad.doubleclick.net^",
    "||pubads.g.doubleclick.net^",
    "||securepubads.g.doubleclick.net^",
    "||static.doubleclick.net^",
    "||imasdk.googleapis.com^",
    "||video-ad-stats.googlevideo.com^",
    "||youtube.googleapis.com/youtubei/v1/player/ad_break^",
    "||youtube.com/get_midroll_info^",

    # Smart TV & Device Telemetry
    "||samsungads.com^",
    "||smetrics.samsung.com^",
    "||config.samsungcloudsolution.net^",
    "||lgtvonline.lge.com^",
    "||rdx2.lgtvsdp.com^",
    "||ibs.lgappstv.com^",
    "||scribe.logs.roku.com^",
    "||ads.roku.com^",
    "||tracking.miui.com^",
    "||data.mistat.xiaomi.com^",

    # Crypto Miners, Malvertising & Popunder Spam
    "||coinhive.com^",
    "||coin-hive.com^",
    "||jsecoin.com^",
    "||minr.pw^",
    "||crypto-loot.com^",
    "||authedmine.com^",
    "||monerominer.rocks^",
    "||cryptoloot.pro^"
]

BRAVE_COSMETIC_FILTERS = [
    "##.adsbygoogle",
    "##.ad-banner",
    "##.ad-container",
    "##.advertisement",
    "##.sponsored-post",
    "##.taboola-feed",
    "##.outbrain-recommendations",
    "##.ytp-ad-module",
    "##.ytp-ad-overlay-container",
    "##.video-ads",
    "##.ad-placement",
    "##ytd-ad-slot-renderer",
    "##ytd-promoted-sparkles-web-renderer",
    "##ytd-banner-promo-renderer",
    "##ytd-in-feed-ad-layout-renderer",
    "##ytd-display-ad-renderer",
    "##ytd-statement-banner-renderer",
    "##.sparkles-light-cta",
    "##.ytp-ad-text",
    "##.ytp-ad-preview-container",
    "##.ytp-ad-skip-button-container"
]
